CREATE TABLE atp.cars
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand               VARCHAR(255),
    model               VARCHAR(255),
    registration_number VARCHAR(255),
    CONSTRAINT pk_cars PRIMARY KEY (id)
);

ALTER TABLE atp.cars
    ADD CONSTRAINT uc_cars_registration_number UNIQUE (registration_number);